/**
 * Türkiye'de satışta olan doğrulanmış elektrikli araç modelleri.
 * Fiyatlar ve teknik veriler resmi distribütör listeleri ve WLTP normlarına dayanır.
 */

export const VEHICLES_SOURCE = "Marka Resmi Fiyat Listesi & WLTP";
export const VEHICLES_VERIFIED_AT = "2026-08-01";

export const vehicles = [
  {
    brand: "Togg",
    model: "T10X V2 RWD Uzun Menzil",
    year: 2026,
    segment: "C-SUV",
    bodyType: "SUV",
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
    price: 1823000,
    otvRate: 10,
    rangeKm: 523,
    batteryKwh: 88.5,
    motorPowerKw: 160,
    motorPowerHp: 218,
    acceleration: 7.8,
    topSpeed: 185,
    consumption: 16.9,
    driveType: "RWD",
    isFeatured: true,
    dcChargeKw: 180,
    chargeMin: 28,
    trunkLiter: 441,
    warranty: "3 yıl / 100.000 km araç, 8 yıl / 160.000 km batarya",
    rating: 8.8,
    rangeSummerKm: 480,
    rangeWinterKm: 390,
    rangeSource: "WLTP & Saha Testleri",
    pros: ["Geniş iç hacim", "Zengin dijital kokpit", "Hızlı DC şarj", "Yerli servis ağı"],
    cons: ["Yazılım güncellemeleri zaman alabiliyor", "Arka görüş açısı dar"],
    description: "Türkiye'nin yerli elektrikli C-SUV modeli Togg T10X, 88.5 kWh bataryası ve 523 km WLTP menzili ile segmentinde iddialı."
  },
  {
    brand: "Togg",
    model: "T10X V1 RWD Standart Menzil",
    year: 2026,
    segment: "C-SUV",
    bodyType: "SUV",
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
    price: 1432600,
    otvRate: 10,
    rangeKm: 314,
    batteryKwh: 52.4,
    motorPowerKw: 160,
    motorPowerHp: 218,
    acceleration: 7.4,
    topSpeed: 185,
    consumption: 16.7,
    driveType: "RWD",
    isFeatured: false,
    dcChargeKw: 150,
    chargeMin: 28,
    trunkLiter: 441,
    warranty: "3 yıl / 100.000 km araç, 8 yıl / 160.000 km batarya",
    rating: 8.2,
    rangeSummerKm: 290,
    rangeWinterKm: 235,
    rangeSource: "WLTP Karma",
    pros: ["Fiyat/performans oranı", "Yüksek standart güvenlik", "Geniş ekran deneyimi"],
    cons: ["Şehir dışı seyahatlerde daha sık şarj ihtiyacı"],
    description: "T10X'in standart menzilli versiyonu, şehir içi ve banliyö kullanımı için dengeli bir seçenek sunuyor."
  },
  {
    brand: "Tesla",
    model: "Model Y Arkadan İtiş",
    year: 2026,
    segment: "D-SUV",
    bodyType: "SUV",
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80",
    price: 1795000,
    otvRate: 10,
    rangeKm: 455,
    batteryKwh: 60.0,
    motorPowerKw: 159,
    motorPowerHp: 216,
    acceleration: 6.9,
    topSpeed: 217,
    consumption: 15.7,
    driveType: "RWD",
    isFeatured: true,
    dcChargeKw: 170,
    chargeMin: 20,
    trunkLiter: 854,
    warranty: "4 yıl / 80.000 km araç, 8 yıl / 160.000 km batarya",
    rating: 9.2,
    rangeSummerKm: 420,
    rangeWinterKm: 340,
    rangeSource: "EPA & WLTP",
    pros: ["Geniş bagaj ve frunk", "Supercharger ağı erişimi", "Mükemmel enerji verimliliği", "Akıcı multimedya"],
    cons: ["Sert süspansiyon yapısı", "Fiziksel tuş eksikliği"],
    description: "%10 ÖTV dilimine özel 159 kW motoruyla Tesla Model Y RWD, geniş iç hacmi ve verimliliğiyle Türkiye'nin en çok satan elektrikli modellerinden biri."
  },
  {
    brand: "Tesla",
    model: "Model Y Long Range AWD",
    year: 2026,
    segment: "D-SUV",
    bodyType: "SUV",
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80",
    price: 3250000,
    otvRate: 60,
    rangeKm: 533,
    batteryKwh: 78.1,
    motorPowerKw: 378,
    motorPowerHp: 514,
    acceleration: 5.0,
    topSpeed: 217,
    consumption: 16.9,
    driveType: "AWD",
    isFeatured: false,
    dcChargeKw: 250,
    chargeMin: 27,
    trunkLiter: 854,
    warranty: "4 yıl / 80.000 km araç, 8 yıl / 192.000 km batarya",
    rating: 9.0,
    rangeSummerKm: 500,
    rangeWinterKm: 410,
    rangeSource: "WLTP",
    pros: ["Çift motorlu dört çeker çekiş", "Yüksek performans", "Geniş bagaj"],
    cons: ["Yüksek ÖTV dilimi"],
    description: "Çift motorlu dört çeker sistemi ve 533 km WLTP menzili ile her yol koşuluna uygun uzun yol canavarı."
  },
  {
    brand: "BYD",
    model: "Atto 3 Design",
    year: 2026,
    segment: "C-SUV",
    bodyType: "SUV",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=1200&q=80",
    price: 1590000,
    otvRate: 10,
    rangeKm: 420,
    batteryKwh: 60.4,
    motorPowerKw: 150,
    motorPowerHp: 204,
    acceleration: 7.3,
    topSpeed: 160,
    consumption: 15.6,
    driveType: "FWD",
    isFeatured: true,
    dcChargeKw: 88,
    chargeMin: 44,
    trunkLiter: 440,
    warranty: "6 yıl / 150.000 km araç, 8 yıl / 200.000 km batarya",
    rating: 8.6,
    rangeSummerKm: 390,
    rangeWinterKm: 310,
    rangeSource: "WLTP Karma",
    pros: ["Güvenli Blade Batarya teknolojisi", "Zengin standart donanım", "Dönebilen multimedya ekranı"],
    cons: ["DC şarj hızı 88 kW ile sınırlı", "Otoyol hızlarında tüketim artışı"],
    description: "BYD'nin e-Platform 3.0 üzerine inşa edilen ve Blade Batarya ile gelen C-SUV modeli Atto 3."
  },
  {
    brand: "BYD",
    model: "Seal Excellence AWD",
    year: 2026,
    segment: "D-Sedan",
    bodyType: "Sedan",
    image: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80",
    price: 2450000,
    otvRate: 40,
    rangeKm: 520,
    batteryKwh: 82.5,
    motorPowerKw: 390,
    motorPowerHp: 530,
    acceleration: 3.8,
    topSpeed: 180,
    consumption: 18.2,
    driveType: "AWD",
    isFeatured: false,
    dcChargeKw: 150,
    chargeMin: 26,
    trunkLiter: 400,
    warranty: "6 yıl / 150.000 km araç, 8 yıl / 200.000 km batarya",
    rating: 8.9,
    rangeSummerKm: 490,
    rangeWinterKm: 390,
    rangeSource: "WLTP",
    pros: ["3.8 saniye 0-100 km/s hızlanma", "Sportif sürüş dinamiği", "Kaliteli kabin malzemeleri"],
    cons: ["Arka baş mesafesi uzun boylular için kısıtlı"],
    description: "Sportif D segmenti elektrikli sedan BYD Seal, 530 HP gücü ve Cell-to-Body gövde mimarisi ile öne çıkıyor."
  },
  {
    brand: "Hyundai",
    model: "Ioniq 5 Progressive 125 kW",
    year: 2026,
    segment: "D-Crossover",
    bodyType: "Crossover",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    price: 1780000,
    otvRate: 10,
    rangeKm: 440,
    batteryKwh: 63.0,
    motorPowerKw: 125,
    motorPowerHp: 170,
    acceleration: 8.5,
    topSpeed: 185,
    consumption: 16.7,
    driveType: "RWD",
    isFeatured: true,
    dcChargeKw: 240,
    chargeMin: 18,
    trunkLiter: 527,
    warranty: "5 yıl / 100.000 km araç, 8 yıl / 160.000 km batarya",
    rating: 9.1,
    rangeSummerKm: 410,
    rangeWinterKm: 330,
    rangeSource: "WLTP Karma",
    pros: ["800V ultra hızlı şarj mimarisi (18 dk %10-%80)", "Geniş ve ferah iç yaşam alanı", "V2L araçtan güç sağlama"],
    cons: ["Arka silecek eksikliği (bazı versiyonlarda)"],
    description: "E-GMP platformlu Hyundai Ioniq 5, retro-fütüristik tasarımı ve 800V mimarisiyle segmentinin en hızlı şarj olan modellerinden."
  },
  {
    brand: "MG",
    model: "MG4 Electric Luxury",
    year: 2026,
    segment: "C-Hatchback",
    bodyType: "Hatchback",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
    price: 1399000,
    otvRate: 10,
    rangeKm: 435,
    batteryKwh: 64.0,
    motorPowerKw: 150,
    motorPowerHp: 204,
    acceleration: 7.9,
    topSpeed: 160,
    consumption: 16.0,
    driveType: "RWD",
    isFeatured: true,
    dcChargeKw: 140,
    chargeMin: 26,
    trunkLiter: 363,
    warranty: "7 yıl / 150.000 km garanti",
    rating: 8.7,
    rangeSummerKm: 400,
    rangeWinterKm: 320,
    rangeSource: "WLTP Karma",
    pros: ["50:50 ağırlık dağılımı ve arkadan itiş", "7 yıl garanti", "Erişilebilir fiyat"],
    cons: ["Multimedya arayüz hızı ortalama"],
    description: "Arkadan itişli dinamik C hatchback MG4 Electric, sürüş keyfi ve fiyat avantajı ile dikkat çekiyor."
  },
  {
    brand: "Volvo",
    model: "EX30 Single Motor Extended Range",
    year: 2026,
    segment: "B-SUV",
    bodyType: "SUV",
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
    price: 1980000,
    otvRate: 10,
    rangeKm: 476,
    batteryKwh: 69.0,
    motorPowerKw: 200,
    motorPowerHp: 272,
    acceleration: 5.3,
    topSpeed: 180,
    consumption: 15.7,
    driveType: "RWD",
    isFeatured: true,
    dcChargeKw: 153,
    chargeMin: 26,
    trunkLiter: 318,
    warranty: "3 yıl garanti, 8 yıl / 160.000 km batarya",
    rating: 8.9,
    rangeSummerKm: 440,
    rangeWinterKm: 350,
    rangeSource: "WLTP",
    pros: ["İskandinav minimalist tasarım", "272 HP güçlü performans", "Google entegreli multimedya"],
    cons: ["Kompakt arka diz mesafesi", "Tek merkez ekran alışkanlık gerektirir"],
    description: "Volvo'nun en küçük SUV'u EX30, kompakt boyutları, güçlü motoru ve çevre dostu malzemeleriyle öne çıkıyor."
  },
  {
    brand: "Renault",
    model: "Megane E-Tech Iconic EV60",
    year: 2026,
    segment: "C-Crossover",
    bodyType: "Crossover",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
    price: 1750000,
    otvRate: 10,
    rangeKm: 450,
    batteryKwh: 60.0,
    motorPowerKw: 160,
    motorPowerHp: 220,
    acceleration: 7.4,
    topSpeed: 160,
    consumption: 15.8,
    driveType: "FWD",
    isFeatured: false,
    dcChargeKw: 130,
    chargeMin: 30,
    trunkLiter: 440,
    warranty: "3 yıl / 100.000 km, 8 yıl / 160.000 km batarya",
    rating: 8.5,
    rangeSummerKm: 420,
    rangeWinterKm: 330,
    rangeSource: "WLTP",
    pros: ["OpenR Link Google Automotive işletim sistemi", "Şık iç mekan", "22 kW AC şarj desteği"],
    cons: ["Dar arka cam ve kalın C sütunu"],
    description: "Renault Megane E-Tech, 22 kW dahili AC şarj desteği ve Google entegrasyonlu OpenR ekranıyla pratik bir elektrikli deneyim sunar."
  },
  {
    brand: "Kia",
    model: "EV6 Prestige 168 kW RWD",
    year: 2026,
    segment: "D-Crossover",
    bodyType: "Crossover",
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80",
    price: 2150000,
    otvRate: 40,
    rangeKm: 528,
    batteryKwh: 77.4,
    motorPowerKw: 168,
    motorPowerHp: 229,
    acceleration: 7.3,
    topSpeed: 185,
    consumption: 16.5,
    driveType: "RWD",
    isFeatured: false,
    dcChargeKw: 233,
    chargeMin: 18,
    trunkLiter: 520,
    warranty: "5 yıl / 150.000 km garanti",
    rating: 9.0,
    rangeSummerKm: 495,
    rangeWinterKm: 400,
    rangeSource: "WLTP",
    pros: ["800V süper hızlı şarj mimarisi", "528 km uzun menzil", "Dinamik yol tutuş"],
    cons: ["Sert süspansiyon ayarı"],
    description: "Avrupa'da Yılın Otomobili seçilen Kia EV6, sportif crossover silüeti ve 800V şarj hızı ile dikkat çekiyor."
  },
  {
    brand: "BMW",
    model: "i4 eDrive40 M Sport",
    year: 2026,
    segment: "D-Gran Coupe",
    bodyType: "Sedan",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    price: 3650000,
    otvRate: 60,
    rangeKm: 590,
    batteryKwh: 83.9,
    motorPowerKw: 250,
    motorPowerHp: 340,
    acceleration: 5.6,
    topSpeed: 190,
    consumption: 16.1,
    driveType: "RWD",
    isFeatured: true,
    dcChargeKw: 205,
    chargeMin: 31,
    trunkLiter: 470,
    warranty: "2 yıl sınırsız km, 8 yıl / 160.000 km batarya",
    rating: 9.3,
    rangeSummerKm: 550,
    rangeWinterKm: 450,
    rangeSource: "WLTP",
    pros: ["Geleneksel BMW sürüş dinamikleri", "590 km etkileyici menzil", "Kaliteli kabin ve iDrive"],
    cons: ["Şaft tüneli varlığı (ortak platform)"],
    description: "Elektrikli Gran Coupé BMW i4 eDrive40, 590 km WLTP menzili ve arkadan itişli safkan BMW sürüş karakteriyle premium segmentin gözdesi."
  },
  {
    brand: "Peugeot",
    model: "E-2008 GT",
    year: 2026,
    segment: "B-SUV",
    bodyType: "SUV",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
    price: 1680000,
    otvRate: 10,
    rangeKm: 406,
    batteryKwh: 54.0,
    motorPowerKw: 115,
    motorPowerHp: 156,
    acceleration: 9.1,
    topSpeed: 150,
    consumption: 15.2,
    driveType: "FWD",
    isFeatured: false,
    dcChargeKw: 100,
    chargeMin: 30,
    trunkLiter: 434,
    warranty: "3 yıl / 100.000 km, 8 yıl / 160.000 km batarya",
    rating: 8.3,
    rangeSummerKm: 380,
    rangeWinterKm: 295,
    rangeSource: "WLTP",
    pros: ["Etkileyici i-Cockpit tasarımı", "Düşük şehir içi tüketim", "Geniş bagaj"],
    cons: ["Otoyol hızlanma performansı sınırlı"],
    description: "Makyajlı tasarımı, 54 kWh yeni bataryası ve 156 HP motoruyla Peugeot E-2008, B-SUV segmentinde stil sahibi bir seçenek."
  }
];
