export interface FallbackStation {
  id: string;
  name: string;
  operator: string;
  city: string;
  district: string;
  lat: number;
  lng: number;
  maxPowerKw: number;
  socketCount: number;
  isFast: boolean;
  price: number;
}

export const FALLBACK_STATIONS: FallbackStation[] = [
  // İSTANBUL & MARMARA
  {
    id: "fb-ist-1",
    name: "Trugo - O-7 Kuzey Marmara Otoyolu Dinlenme Tesisi",
    operator: "Trugo",
    city: "İstanbul",
    district: "Eyüpsultan",
    lat: 41.1895,
    lng: 28.8452,
    maxPowerKw: 300,
    socketCount: 6,
    isFast: true,
    price: 8.49,
  },
  {
    id: "fb-ist-2",
    name: "Tesla Supercharger - Viaport Asia Kurtköy",
    operator: "Tesla",
    city: "İstanbul",
    district: "Pendik",
    lat: 40.9298,
    lng: 29.3242,
    maxPowerKw: 250,
    socketCount: 8,
    isFast: true,
    price: 7.80,
  },
  {
    id: "fb-ist-3",
    name: "ZES - Zorlu Center DC Şarj İstasyonu",
    operator: "ZES",
    city: "İstanbul",
    district: "Beşiktaş",
    lat: 41.0667,
    lng: 29.0175,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.90,
  },
  {
    id: "fb-ist-4",
    name: "Eşarj - Mall of İstanbul AVM DC",
    operator: "Eşarj",
    city: "İstanbul",
    district: "Başakşehir",
    lat: 41.0633,
    lng: 28.8078,
    maxPowerKw: 120,
    socketCount: 4,
    isFast: true,
    price: 8.80,
  },
  {
    id: "fb-ist-5",
    name: "Astor Şarj - Kadıköy Kozyatağı HPC",
    operator: "Astor",
    city: "İstanbul",
    district: "Kadıköy",
    lat: 40.9765,
    lng: 29.0987,
    maxPowerKw: 200,
    socketCount: 4,
    isFast: true,
    price: 7.95,
  },
  {
    id: "fb-ist-6",
    name: "Voltrun - Ataşehir Metropol İstanbul",
    operator: "Voltrun",
    city: "İstanbul",
    district: "Ataşehir",
    lat: 40.9934,
    lng: 29.1234,
    maxPowerKw: 120,
    socketCount: 2,
    isFast: true,
    price: 8.25,
  },
  {
    id: "fb-ist-7",
    name: "Sharz.net - Bakırköy Sahil DC",
    operator: "Sharz",
    city: "İstanbul",
    district: "Bakırköy",
    lat: 40.9782,
    lng: 28.8741,
    maxPowerKw: 90,
    socketCount: 2,
    isFast: true,
    price: 8.35,
  },
  {
    id: "fb-ist-8",
    name: "Trugo - Maslak 42 HPC Hub",
    operator: "Trugo",
    city: "İstanbul",
    district: "Sarıyer",
    lat: 41.1142,
    lng: 29.0195,
    maxPowerKw: 300,
    socketCount: 6,
    isFast: true,
    price: 8.49,
  },
  // KOCAELİ & BURSA & O-5
  {
    id: "fb-koc-1",
    name: "Trugo - O-4 Anadolu Otoyolu Gebze Tesisleri",
    operator: "Trugo",
    city: "Kocaeli",
    district: "Gebze",
    lat: 40.8032,
    lng: 29.4312,
    maxPowerKw: 300,
    socketCount: 4,
    isFast: true,
    price: 8.49,
  },
  {
    id: "fb-bur-1",
    name: "Trugo - O-5 Oksijen 68 Bursa Kuzey",
    operator: "Trugo",
    city: "Bursa",
    district: "Nilüfer",
    lat: 40.2456,
    lng: 28.9876,
    maxPowerKw: 300,
    socketCount: 6,
    isFast: true,
    price: 8.49,
  },
  {
    id: "fb-bur-2",
    name: "ZES - Bursa Downtown AVM DC",
    operator: "ZES",
    city: "Bursa",
    district: "Osmangazi",
    lat: 40.2134,
    lng: 29.0456,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.90,
  },
  {
    id: "fb-bol-1",
    name: "Trugo - Bolu Dağı Highway Outlet HPC Hub",
    operator: "Trugo",
    city: "Bolu",
    district: "Bolu Merkez",
    lat: 40.7321,
    lng: 31.4876,
    maxPowerKw: 300,
    socketCount: 8,
    isFast: true,
    price: 8.49,
  },
  {
    id: "fb-bol-2",
    name: "Tesla Supercharger - Bolu Dağı Highway",
    operator: "Tesla",
    city: "Bolu",
    district: "Bolu Merkez",
    lat: 40.7315,
    lng: 31.4892,
    maxPowerKw: 250,
    socketCount: 8,
    isFast: true,
    price: 7.80,
  },
  // ANKARA & İÇ ANADOLU
  {
    id: "fb-ank-1",
    name: "Trugo - Ankara Panora AVM HPC",
    operator: "Trugo",
    city: "Ankara",
    district: "Çankaya",
    lat: 39.8512,
    lng: 32.8423,
    maxPowerKw: 300,
    socketCount: 4,
    isFast: true,
    price: 8.49,
  },
  {
    id: "fb-ank-2",
    name: "Tesla Supercharger - Armada AVM Ankara",
    operator: "Tesla",
    city: "Ankara",
    district: "Yenimahalle",
    lat: 39.9142,
    lng: 32.8091,
    maxPowerKw: 250,
    socketCount: 8,
    isFast: true,
    price: 7.80,
  },
  {
    id: "fb-ank-3",
    name: "ZES - Ankara Kentpark AVM DC",
    operator: "ZES",
    city: "Ankara",
    district: "Çankaya",
    lat: 39.9098,
    lng: 32.7785,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.90,
  },
  {
    id: "fb-ank-4",
    name: "Astor Şarj - ASO 1. OSB Sincan HPC",
    operator: "Astor",
    city: "Ankara",
    district: "Sincan",
    lat: 39.9654,
    lng: 32.5543,
    maxPowerKw: 300,
    socketCount: 6,
    isFast: true,
    price: 7.95,
  },
  {
    id: "fb-esk-1",
    name: "Eşarj - Eskişehir Vega Outlet DC",
    operator: "Eskişehir",
    district: "Tepebaşı",
    lat: 39.7891,
    lng: 30.5012,
    maxPowerKw: 120,
    socketCount: 2,
    isFast: true,
    price: 8.80,
  },
  {
    id: "fb-kon-1",
    name: "Trugo - Konya M1 AVM HPC",
    operator: "Trugo",
    city: "Konya",
    district: "Selçuklu",
    lat: 37.9543,
    lng: 32.5123,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.49,
  },
  // İZMİR & EGE
  {
    id: "fb-izm-1",
    name: "Trugo - İzmir İstinyePark HPC Hub",
    operator: "Trugo",
    city: "İzmir",
    district: "Balçova",
    lat: 38.3982,
    lng: 27.0451,
    maxPowerKw: 300,
    socketCount: 6,
    isFast: true,
    price: 8.49,
  },
  {
    id: "fb-izm-2",
    name: "Tesla Supercharger - Forum Bornova İzmir",
    operator: "Tesla",
    city: "İzmir",
    district: "Bornova",
    lat: 38.4567,
    lng: 27.2145,
    maxPowerKw: 250,
    socketCount: 8,
    isFast: true,
    price: 7.80,
  },
  {
    id: "fb-izm-3",
    name: "ZES - Alsancak Liman DC",
    operator: "ZES",
    city: "İzmir",
    district: "Konak",
    lat: 38.4389,
    lng: 27.1498,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.90,
  },
  {
    id: "fb-man-1",
    name: "Trugo - O-5 Oksijen 244 Manisa",
    operator: "Trugo",
    city: "Manisa",
    district: "Kırkağaç",
    lat: 39.1123,
    lng: 27.6745,
    maxPowerKw: 300,
    socketCount: 4,
    isFast: true,
    price: 8.49,
  },
  {
    id: "fb-mug-1",
    name: "ZES - Bodrum Midtown AVM DC",
    operator: "ZES",
    city: "Muğla",
    district: "Bodrum",
    lat: 37.0543,
    lng: 27.3876,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.90,
  },
  // AKDENİZ & ANTALYA
  {
    id: "fb-ant-1",
    name: "Trugo - Antalya TerraCity AVM HPC",
    operator: "Trugo",
    city: "Antalya",
    district: "Muratpaşa",
    lat: 36.8523,
    lng: 30.7541,
    maxPowerKw: 300,
    socketCount: 6,
    isFast: true,
    price: 8.49,
  },
  {
    id: "fb-ant-2",
    name: "Tesla Supercharger - Antalya Mall of Antalya",
    operator: "Tesla",
    city: "Antalya",
    district: "Kepez",
    lat: 36.9321,
    lng: 30.7891,
    maxPowerKw: 250,
    socketCount: 8,
    isFast: true,
    price: 7.80,
  },
  {
    id: "fb-ada-1",
    name: "ZES - Adana 01 Burda AVM DC",
    operator: "ZES",
    city: "Adana",
    district: "Seyhan",
    lat: 36.9982,
    lng: 35.3123,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.90,
  },
  {
    id: "fb-gaz-1",
    name: "Trugo - Gaziantep Sanko Park AVM",
    operator: "Trugo",
    city: "Gaziantep",
    district: "Şehitkamil",
    lat: 37.0654,
    lng: 37.3654,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.49,
  },
  // KARADENİZ
  {
    id: "fb-sam-1",
    name: "Trugo - Samsun Piazza AVM HPC",
    operator: "Trugo",
    city: "Samsun",
    district: "Canik",
    lat: 41.2876,
    lng: 36.3541,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.49,
  },
  {
    id: "fb-tra-1",
    name: "ZES - Trabzon Forum AVM DC",
    operator: "ZES",
    city: "Trabzon",
    district: "Ortahisar",
    lat: 40.9987,
    lng: 39.7541,
    maxPowerKw: 180,
    socketCount: 4,
    isFast: true,
    price: 8.90,
  },
];
